# Generated by Django 5.1.4 on 2025-01-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_stripeeventlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeEventLog',
        ),
    ]
