# Generated by Django 5.1.4 on 2025-01-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketuser',
            name='firstname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketuser',
            name='lastname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
