# Generated by Django 5.1.4 on 2025-01-13 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdeveloper',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.platformsubscription'),
        ),
    ]
