# Generated by Django 5.1.4 on 2025-01-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdeveloperinterest',
            name='other',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
