# Generated by Django 5.1.4 on 2024-12-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='uri_hash',
            field=models.CharField(default='1f99925b93194b70', max_length=16, unique=True),
        ),
    ]
