# Generated by Django 5.1.4 on 2025-01-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketuser',
            name='privacy_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketuser',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
