# Generated by Django 5.1.4 on 2025-01-15 10:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketuser',
            name='company_website',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[accounts.models.validate_url]),
        ),
        migrations.AlterField(
            model_name='marketuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
