# Generated by Django 5.1.4 on 2024-12-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_invitelink_uri_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitelink",
            name="uri_hash",
            field=models.CharField(
                default="01522e7a3c6b4da3", max_length=16, unique=True
            ),
        ),
    ]
