# Generated by Django 5.1.4 on 2025-01-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_marketuser_firstname_marketuser_lastname'),
        ('accounts', '0002_marketuser_privacy_accepted_and_more'),
    ]

    operations = [
    ]
