# Generated by Django 5.1.4 on 2024-12-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_invitelink_uri_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='uri_hash',
            field=models.CharField(default='d39c5c4d202e451c', max_length=16, unique=True),
        ),
    ]
