# Generated by Django 5.1.4 on 2025-01-10 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_projectdeveloperinterest_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landowner',
            name='position',
        ),
        migrations.AddField(
            model_name='marketuser',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectdeveloper',
            name='employees',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='projectdeveloper',
            name='founding_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AddField(
            model_name='projectdeveloper',
            name='mw_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
