# Generated by Django 5.1.4 on 2025-01-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20250109_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketuser',
            name='role',
            field=models.CharField(choices=[('landowner', 'Landowner'), ('developer', 'Project Developer')], max_length=20),
        ),
    ]
