# Generated by Django 5.1.4 on 2025-01-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20250109_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketuser',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='marketuser',
            name='current_plan',
            field=models.CharField(default='Free', max_length=20),
        ),
    ]
