# Generated by Django 5.1.4 on 2024-12-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_invitelink_uri_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='uri_hash',
            field=models.CharField(default='f007bfcb5708455a', max_length=16, unique=True),
        ),
    ]
