# Generated by Django 5.1.4 on 2025-01-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_marketuser_company_logo_marketuser_current_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdeveloperinterest',
            name='other',
            field=models.BooleanField(),
        ),
    ]
