# Generated by Django 5.1.4 on 2025-01-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_projectdeveloperinterest_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketuser',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='marketuser',
            name='current_plan',
        ),
        migrations.AlterField(
            model_name='projectdeveloperinterest',
            name='other',
            field=models.CharField(max_length=50),
        ),
    ]
