# Generated by Django 5.1.4 on 2025-01-10 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_marketuser_role'),
        ('accounts', '0006_remove_marketuser_company_logo_and_more'),
    ]

    operations = [
    ]
