# Generated by Django 5.1.4 on 2025-01-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="alkis_feature_id",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
    ]
