# Generated by Django 5.1.4 on 2025-01-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcel",
            name="plot_number_secondary",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
