# Generated by Django 5.1.4 on 2025-01-13 17:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaofferconfirmation',
            name='id',
        ),
        migrations.AddField(
            model_name='areaofferconfirmation',
            name='contracted_term_month',
            field=models.PositiveSmallIntegerField(help_text='Vertragslaufzeit', null=True),
        ),
        migrations.AddField(
            model_name='areaofferconfirmation',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro')], default='EUR'),
        ),
        migrations.AddField(
            model_name='areaofferconfirmation',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='areaofferconfirmation',
            name='lease_amount_single_payment',
            field=models.DecimalField(decimal_places=2, default=200, help_text='Einmalzahlung an Eigentümer bei Vertragsabschluss', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areaofferconfirmation',
            name='lease_amount_yearly_lease_year_one',
            field=models.DecimalField(decimal_places=2, default=120, help_text='Jährliche Pacht in Jahr 1', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areaofferconfirmation',
            name='message_to_landowner',
            field=models.TextField(default='', help_text='Ihre Nachricht an den Eigentümer zu dem Gebot', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areaofferconfirmation',
            name='message_to_platform',
            field=models.TextField(default='', help_text='Ihre Nachricht an Agrario Energy', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areaofferconfirmation',
            name='sale_amount',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Angebotener Kaufpreis', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areaofferconfirmation',
            name='share_of_income',
            field=models.TextField(choices=[('YES', 'Ja'), ('NO', 'Nein'), ('NOT', 'Keine Angabe')], default='YES', help_text='Bieten Sie Beteiligungen an laufenden Erlösen?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areaofferconfirmation',
            name='shares_project_company',
            field=models.TextField(choices=[('YES', 'Ja'), ('NO', 'Nein'), ('NOT', 'Keine Angabe')], default='YES', help_text='Im Falle der Gründung einer Projektgesellschaft: Bieten Sie Beteiligungen an der Projektgesellschaft an?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areaofferconfirmation',
            name='staggered_lease',
            field=models.TextField(choices=[('YES', 'Ja'), ('NO', 'Nein'), ('NOT', 'Keine Angabe')], help_text='Staffelpacht möglich?', null=True),
        ),
        migrations.AddField(
            model_name='areaofferconfirmation',
            name='utilitization',
            field=models.CharField(choices=[('NO', 'No Restriction'), ('SA', 'Sale'), ('LE', 'Lease')], default='V'),
            preserve_default=False,
        ),
    ]
