# Generated by Django 5.1.4 on 2025-01-11 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='areaoffer',
            old_name='description',
            new_name='important_remarks',
        ),
        migrations.RemoveField(
            model_name='areaoffer',
            name='title',
        ),
        migrations.AddField(
            model_name='areaoffer',
            name='preferred_regionality',
            field=models.TextField(choices=[('NO', 'Keine Einschränkung'), ('DE', 'Firmensitz in Deutschland'), ('BL', 'Firmensitz im Bundesland des Grundstücks')], default='NO'),
        ),
        migrations.AddField(
            model_name='areaoffer',
            name='shareholder_model',
            field=models.TextField(choices=[('NO', 'Keine Einschränkung'), ('IN', 'Beteiligungen am Erlös'), ('CO', 'Beteiligungen an der Projektgesellschaft'), ('BO', 'Beides')], default='NO'),
        ),
        migrations.AlterField(
            model_name='areaoffer',
            name='status',
            field=models.CharField(choices=[('V', 'In Vorbereitung'), ('P', 'Vorprüfung abgeschlossen'), ('A', 'Aktiv'), ('I', 'Inaktiv')], default='V', max_length=2),
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.parcel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'parcel')},
            },
        ),
    ]
