# Generated by Django 5.1.4 on 2025-01-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="analyse_plus",
            field=models.BooleanField(default=False),
        ),
    ]
