# Generated by Django 5.1.4 on 2024-12-20 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaoffer',
            name='bidding_conditions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areaoffer',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='linked_offers', to='offers.areaofferdocuments'),
        ),
        migrations.AlterField(
            model_name='areaofferdocuments',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documented_offers', to='offers.areaoffer'),
        ),
    ]
