# Generated by Django 5.1.4 on 2024-12-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaoffer',
            name='criteria',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
