# Generated by Django 5.1.4 on 2025-01-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_basketitem'),
        ('offers', '0002_rename_description_areaoffer_important_remarks_and_more'),
    ]

    operations = [
    ]
