# Generated by Django 5.1.4 on 2025-01-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0002_parcel_alkis_feature_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="zipcode",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
    ]
