# Generated by Django 5.1.4 on 2025-01-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_remove_areaofferconfirmation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaofferconfirmation',
            name='contracted_term_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Vertragslaufzeit', null=True),
        ),
        migrations.AlterField(
            model_name='areaofferconfirmation',
            name='lease_amount_single_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Einmalzahlung an Eigentümer bei Vertragsabschluss', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='areaofferconfirmation',
            name='lease_amount_yearly_lease_year_one',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Jährliche Pacht in Jahr 1', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='areaofferconfirmation',
            name='sale_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Angebotener Kaufpreis', max_digits=10, null=True),
        ),
    ]
