# Generated by Django 5.1.4 on 2025-01-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_areaofferconfirmation_contracted_term_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaofferconfirmation',
            name='utilitization',
        ),
        migrations.AddField(
            model_name='areaofferconfirmation',
            name='utilization',
            field=models.CharField(choices=[('SA', 'Kauf des Gründstücks'), ('LE', 'Anpachtung des Grundstücks'), ('BO', 'Beides')], default='SA', help_text='Nutzungsart durch den Eigentümer', max_length=2),
            preserve_default=False,
        ),
    ]
