# Generated by Django 5.1.4 on 2024-12-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='landuse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
