# Generated by Django 5.1.4 on 2025-01-10 20:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0003_parcel_zipcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcel",
            name="polygon",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
