# Generated by Django 5.1.4 on 2025-01-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0004_alter_parcel_polygon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcel",
            name="cadastral_area",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="cadastral_sector",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="district_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="municipality_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="state_name",
            field=models.CharField(max_length=255),
        ),
    ]
