# Generated by Django 5.1.4 on 2025-01-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_remove_areaofferconfirmation_utilitization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaofferconfirmation',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro')], default='EUR', max_length=10),
        ),
    ]
