# Generated by Django 5.1.4 on 2025-01-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0005_alter_parcel_cadastral_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcel",
            name="land_use",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
