# Generated by Django 5.1.4 on 2025-01-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0007_alter_parcel_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcel",
            name="zipcode",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
