# Generated by Django 5.1.4 on 2025-01-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0008_alter_parcel_zipcode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parcel",
            old_name="cadastral_sector",
            new_name="cadastrel_parcel",
        ),
        migrations.AddField(
            model_name="parcel",
            name="communal_district",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
    ]
