# Generated by Django 5.1.4 on 2025-01-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0009_rename_cadastral_sector_parcel_cadastrel_parcel_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parcel",
            old_name="cadastrel_parcel",
            new_name="cadastral_parcel",
        ),
    ]
