# Generated by Django 5.1.4 on 2025-01-14 22:00

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('purchase_type', models.CharField(choices=[('analyse', 'Analyse'), ('analyse_plus', 'Analyse Plus')], default='analyse', max_length=20)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('area_m2', models.PositiveIntegerField()),
                ('usable_area_m2', models.PositiveIntegerField()),
                ('usable_area_solar_m2', models.PositiveIntegerField()),
                ('usable_area_wind_m2', models.PositiveIntegerField()),
                ('usable_area_battery_m2', models.PositiveIntegerField()),
                ('energy_distance_midhigh_m', models.PositiveIntegerField()),
                ('energy_distance_highhigh_m', models.PositiveIntegerField()),
                ('energy_distance_tower_highest_m', models.PositiveIntegerField()),
                ('energy_distance_tower_high_m', models.PositiveIntegerField()),
                ('energy_distance_tower_mid_m', models.PositiveIntegerField()),
                ('distance_motorway_ramp_m', models.PositiveIntegerField()),
                ('distance_motorway_m', models.PositiveIntegerField()),
                ('distance_trunkprimary_m', models.PositiveIntegerField()),
                ('distance_secondary_m', models.PositiveIntegerField()),
                ('distance_traintracks_m', models.PositiveIntegerField()),
                ('distance_settlement_m', models.PositiveIntegerField()),
                ('eeg_area_m2', models.PositiveIntegerField()),
                ('baugb_area_m2', models.PositiveIntegerField()),
                ('is_area_in_privilege_area', models.BooleanField()),
                ('visible_for', models.CharField(choices=[('A', 'Admin'), ('U', 'User'), ('P', 'Public')], default='U', max_length=1)),
                ('data', models.JSONField()),
                ('parcels', models.ManyToManyField(related_name='reports', to='offers.parcel')),
            ],
        ),
    ]
