# Generated by Django 5.1.4 on 2025-01-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='purchase_type',
            field=models.CharField(choices=[('analyse', 'Analyse'), ('analyse_plus', 'Analyse Plus')], default='analyse', max_length=20),
        ),
    ]
