# Generated by Django 5.1.4 on 2025-01-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_rename_read_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_admin_message',
            field=models.BooleanField(default=False),
        ),
    ]
