# Generated by Django 5.1.4 on 2024-12-24 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectdevelopersubscription",
            name="by_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                unique_for_date="valid_from",
            ),
        ),
        migrations.AlterField(
            model_name="projectdevelopersubscriptiondiscount",
            name="discount_for_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                unique_for_date="valid_from",
            ),
        ),
    ]
