# Generated by Django 5.1.4 on 2025-01-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0003_alter_invitelink_uri_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='uri_hash',
            field=models.CharField(default='cbdcbbdfb92e43ae', max_length=16, unique=True),
        ),
    ]
