# Generated by Django 5.1.4 on 2025-01-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0004_alter_invitelink_uri_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='uri_hash',
            field=models.CharField(default='c1d7ebfda93e46b9', max_length=16, unique=True),
        ),
    ]
