# Generated by Django 5.1.4 on 2025-01-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0004_alter_invitelink_uri_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='uri_hash',
            field=models.CharField(default='5a7c8d323f7e41c0', max_length=16, unique=True),
        ),
    ]
