# Generated by Django 5.1.4 on 2025-01-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invites", "0006_alter_invitelink_uri_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitelink",
            name="uri_hash",
            field=models.CharField(
                default="361118222b3d4d7f", max_length=16, unique=True
            ),
        ),
    ]
