# Generated by Django 5.1.4 on 2025-01-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0006_alter_invitelink_uri_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='uri_hash',
            field=models.CharField(default='0277ee08997c4bdb', max_length=16, unique=True),
        ),
    ]
