# Generated by Django 5.1.4 on 2025-01-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0008_alter_invitelink_uri_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='uri_hash',
            field=models.CharField(default='c2c94aa1f7af4e46', max_length=16, unique=True),
        ),
    ]
