# Generated by Django 5.1.4 on 2025-01-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invites", "0010_alter_invitelink_uri_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitelink",
            name="uri_hash",
            field=models.CharField(
                default="a2ed59d1eb3642a9", max_length=16, unique=True
            ),
        ),
    ]
