# Generated by Django 5.1.4 on 2025-01-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invites", "0011_alter_invitelink_uri_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitelink",
            name="uri_hash",
            field=models.CharField(
                default="2c10d16d710048a7", max_length=16, unique=True
            ),
        ),
    ]
