# Generated by Django 5.1.4 on 2025-01-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invites", "0012_alter_invitelink_uri_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitelink",
            name="uri_hash",
            field=models.CharField(
                default="17048714fad64d5a", max_length=16, unique=True
            ),
        ),
    ]
