name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Test and Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ufav6e2g8vvcga
          POSTGRES_PASSWORD: pa48301d496c284ee80258e838b1531f950f963c607bb9a100bf8006a7d0cc7d7
          POSTGRES_DB: ddcrncnopvagu
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Install GDAL and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev
          which gdal-config || echo "gdal-config not found"
          export PATH="/usr/bin:$PATH"
          export GDAL_CONFIG=/usr/bin/gdal-config
          echo "GDAL_CONFIG=/usr/bin/gdal-config" >> $GITHUB_ENV

      - name: Check GDAL Installation
        run: |
          gdal-config --version
          gdalinfo --version
          ls -l /usr/include/gdal

      - name: Set GDAL Environment Variables
        run: |
          export CPLUS_INCLUDE_PATH=/usr/include/gdal
          export C_INCLUDE_PATH=/usr/include/gdal
          echo "CPLUS_INCLUDE_PATH=/usr/include/gdal" >> $GITHUB_ENV
          echo "C_INCLUDE_PATH=/usr/include/gdal" >> $GITHUB_ENV

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python manage.py test

      - name: Run Migrations
        run: |
          python manage.py migrate

      - name: Collect Static Files
        run: |
          python manage.py collectstatic --noinput

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Install GDAL and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev
          export PATH="/usr/bin:$PATH"
          export GDAL_CONFIG=/usr/bin/gdal-config
          echo "GDAL_CONFIG=/usr/bin/gdal-config" >> $GITHUB_ENV

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Authenticate Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "machine api.heroku.com login ${{ secrets.HEROKU_API_KEY }}" > ~/.netrc
          echo "machine git.heroku.com login ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc
          chmod 600 ~/.netrc
          heroku auth:whoami

      - name: Deploy to Heroku
        run: git push heroku main --force
