name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Test and Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ufav6e2g8vvcga
          POSTGRES_PASSWORD: pa48301d496c284ee80258e838b1531f950f963c607bb9a100bf8006a7d0cc7d7
          POSTGRES_DB: ddcrncnopvagu
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode Firebase Credentials
        env:
          FIREBASE_CREDENTIALS_BASE64: ${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}
        run: |
          echo $FIREBASE_CREDENTIALS_BASE64 | base64 -d > firebase-credentials.json
          echo "FIREBASE_CREDENTIALS_JSON_PATH=firebase-credentials.json" >> $GITHUB_ENV

      - name: Decode Google Credentials
        env:
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
        run: |
          echo $GOOGLE_CREDENTIALS_BASE64 | base64 -d > google-credentials.json
          echo "GOOGLE_CREDENTIALS_JSON_PATH=google-credentials.json" >> $GITHUB_ENV

      - name: Set up PostgreSQL
        env:
          DATABASE_URL: postgres://ufav6e2g8vvcga:pa48301d496c284ee80258e838b1531f950f963c607bb9a100bf8006a7d0cc7d7@c3cj4hehegopde.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/ddcrncnopvagu
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run tests
        run: python manage.py test

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode Firebase Credentials
        env:
          FIREBASE_CREDENTIALS_BASE64: ${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}
        run: |
          echo $FIREBASE_CREDENTIALS_BASE64 | base64 -d > firebase-credentials.json
          echo "FIREBASE_CREDENTIALS_JSON_PATH=firebase-credentials.json" >> $GITHUB_ENV

      - name: Decode Google Credentials
        env:
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
        run: |
          echo $GOOGLE_CREDENTIALS_BASE64 | base64 -d > google-credentials.json
          echo "GOOGLE_CREDENTIALS_JSON_PATH=google-credentials.json" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
          git push heroku main

      - name: Cleanup credentials
        run: |
          rm -f firebase-credentials.json google-credentials.json
