name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger pipeline on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Test and Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ufav6e2g8vvcga
          POSTGRES_PASSWORD: pa48301d496c284ee80258e838b1531f950f963c607bb9a100bf8006a7d0cc7d7
          POSTGRES_DB: ddcrncnopvagu
        ports:
          - 5432:5432

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set up the database
      - name: Set up PostgreSQL
        env:
          DATABASE_URL: postgres://ufav6e2g8vvcga:pa48301d496c284ee80258e838b1531f950f963c607bb9a100bf8006a7d0cc7d7@c3cj4hehegopde.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/ddcrncnopvagu
        run: |
          python manage.py makemigrations
          python manage.py migrate

      # Step 5: Run tests
      - name: Run tests
        env:
          DATABASE_URL: postgres://ufav6e2g8vvcga:pa48301d496c284ee80258e838b1531f950f963c607bb9a100bf8006a7d0cc7d7@c3cj4hehegopde.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/ddcrncnopvagu
        run: python manage.py test

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Decode and Save Firebase Credentials
      - name: Decode Firebase Credentials
        env:
          FIREBASE_CREDENTIALS_BASE64: ${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}
        run: |
          echo $FIREBASE_CREDENTIALS_BASE64 | base64 -d > firebase-credentials.json

      # Step 3: Decode and Save Google Credentials
      - name: Decode Google Credentials
        env:
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
        run: |
          echo $GOOGLE_CREDENTIALS_BASE64 | base64 -d > google-credentials.json

      # Step 4: Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Deploy to Heroku
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
          git push heroku main

      # Step 6: Cleanup Credentials
      - name: Cleanup credentials
        run: |
          rm -f firebase-credentials.json google-credentials.json
