name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Test and Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ufav6e2g8vvcga
          POSTGRES_PASSWORD: pa48301d496c284ee80258e838b1531f950f963c607bb9a100bf8006a7d0cc7d7
          POSTGRES_DB: ddcrncnopvagu
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Add ubuntugis PPA for GDAL 3.9.0
        run: |
          sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev

      - name: Verify GDAL Installation
        run: |
          gdalinfo --version
          python -c "from osgeo import gdal; print(gdal.VersionInfo())"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          export GDAL_CONFIG=/usr/bin/gdal-config
          pip install -r requirements.txt

      - name: Decode Firebase Credentials
        env:
          FIREBASE_CREDENTIALS_BASE64: ${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}
        run: |
          echo $FIREBASE_CREDENTIALS_BASE64 | base64 -d > firebase-credentials.json
          echo "FIREBASE_CREDENTIALS_JSON_PATH=firebase-credentials.json" >> $GITHUB_ENV

      - name: Decode Google Credentials
        env:
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
        run: |
          echo $GOOGLE_CREDENTIALS_BASE64 | base64 -d > google-credentials.json
          echo "GOOGLE_CREDENTIALS_JSON_PATH=google-credentials.json" >> $GITHUB_ENV

      - name: Set Environment Variables
        run: |
          echo "FRONTEND_URL=http://localhost:5173" >> $GITHUB_ENV
          echo "BACKEND_URL=http://127.0.0.1:8000" >> $GITHUB_ENV

      - name: Set up PostgreSQL
        env:
          DATABASE_URL: postgres://ub8kb03rqg26me:p47260b1a24916e34fcf8146e2b71b1c86efcfb512329b9e225fc68865c162474@c97r84s7psuajm.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/dfan664fkppvgj
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run tests
        run: python manage.py test

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Decode Firebase Credentials
        env:
          FIREBASE_CREDENTIALS_BASE64: ${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}
        run: |
          echo $FIREBASE_CREDENTIALS_BASE64 | base64 -d > firebase-credentials.json
          echo "FIREBASE_CREDENTIALS_JSON_PATH=firebase-credentials.json" >> $GITHUB_ENV

      - name: Decode Google Credentials
        env:
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
        run: |
          echo $GOOGLE_CREDENTIALS_BASE64 | base64 -d > google-credentials.json
          echo "GOOGLE_CREDENTIALS_JSON_PATH=google-credentials.json" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Authenticate Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "machine api.heroku.com login ${{ secrets.HEROKU_API_KEY }}" > ~/.netrc
          echo "machine git.heroku.com login ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc
          chmod 600 ~/.netrc
          heroku auth:whoami

      - name: Initialize Git Repository
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-branches origin main
          git fetch --all
          git checkout main
          git branch --set-upstream-to=origin/main main

      - name: Set up Git remote for Heroku
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git || echo "Remote already exists"

      - name: Deploy to Heroku
        run: git push heroku main --force

      - name: Cleanup credentials
        run: |
          rm -f firebase-credentials.json google-credentials.json
